sudo: false

env:
  global:
    - BINSTAR_USER: menpo
  matrix:
    - PYTHON_VERSION: 2.7
    - PYTHON_VERSION: 3.4

matrix:
  allow_failures:
    - env: PYTHON_VERSION=3.4  # waiting on simpleparse

install:
- wget https://raw.githubusercontent.com/menpo/condaci/v0.4.x/condaci.py -O condaci.py
- python condaci.py setup $PYTHON_VERSION --channel $BINSTAR_USER
- export PATH=$HOME/miniconda/bin:$PATH

script:
- python condaci.py auto ./conda --binstarchannel main --binstaruser $BINSTAR_USER --binstarkey $BINSTAR_KEY

notifications:
  slack:
    rooms:
      - menpo:19gyWImMkOfCj0iDAgTbDlDA
    on_success: :change
    on_failure: :change
  email: false
