env:
  global:
    - BINSTAR_USER: menpo
  matrix:
    - PYTHON_VERSION: 2.7
    - PYTHON_VERSION: 3.4

install:
- wget https://raw.githubusercontent.com/jabooth/condaci/v0.2.0/condaci.py -O condaci.py
- python condaci.py setup $PYTHON_VERSION --channel $BINSTAR_USER
- export PATH=$HOME/miniconda/bin:$PATH

script:
- python condaci.py auto ./conda --binstarchannel main --binstaruser $BINSTAR_USER --binstarkey $BINSTAR_KEY

notifications:
  slack: menpo:19gyWImMkOfCj0iDAgTbDlDA
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7599ff4870c99ba51310
    on_success: always
    on_failure: always
    on_start: never
