build: false

environment:
  global:
    BINSTAR_USER: menpo
    BINSTAR_KEY:
      secure: tsajM8eklrwmWI6OdAEKi3FMqIUXUCHS45rPJZ3bwO25PRWi5onvLdsNMk+8vYRS
    PYTHON_VERSION: 2.7
  # matrix:
  #   - PYTHON_VERSION: 2.7
  #   - PYTHON_VERSION: 3.4

matrix:
  fast_finish: true
  # allow_failures:
  #   - platform: x86
  #     PYTHON_VERSION: 3.4
  #   - platform: x64
  #     PYTHON_VERSION: 3.4

platform:
- x86
- x64

init:
- ps: Start-FileDownload 'https://raw.githubusercontent.com/menpo/condaci/v0.4.6/condaci.py' C:\\condaci.py; echo "Done"
- cmd: python C:\\condaci.py setup %PYTHON_VERSION% --channel %BINSTAR_USER%

install:
- cmd: C:\\Miniconda\\python C:\\condaci.py auto ./conda --binstaruser %BINSTAR_USER% --binstarkey %BINSTAR_KEY%

notifications:
  - provider: Slack
    auth_token:
      secure: Jyd2NTPkBrrwBnl1C0mkNp5sUPGXzKrDgpZVDvPj72OUJtovXsO3795UsvktLucG
    channel: general
    on_build_status_changed: true
    on_build_success: false
    on_build_failure: false
