build: false

environment:
  global:
    BINSTAR_USER: menpo
    BINSTAR_KEY:
      secure: tsajM8eklrwmWI6OdAEKi3FMqIUXUCHS45rPJZ3bwO25PRWi5onvLdsNMk+8vYRS
    PYTHON_VERSION: 2.7
  # matrix:
  #   - PYTHON_VERSION: 2.7
  #   - PYTHON_VERSION: 3.4

matrix:
  fast_finish: true
  # allow_failures:
  #   - platform: x86
  #     PYTHON_VERSION: 3.4
  #   - platform: x64
  #     PYTHON_VERSION: 3.4

platform:
- x86
- x64

init:
# If there is a newer build queued for the same PR, cancel this one.
# The AppVeyor 'rollout builds' option is supposed to serve the same
# purpose but it is problematic because it tends to cancel builds pushed
# directly to master instead of just PR builds (or the converse).
# credits: JuliaLang developers.
- ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
    https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
    Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
      throw "There are newer queued builds for this pull request, failing early." }
- ps: Start-FileDownload 'https://raw.githubusercontent.com/menpo/condaci/v0.4.6/condaci.py' C:\\condaci.py; echo "Done"
- cmd: python C:\\condaci.py setup %PYTHON_VERSION% --channel %BINSTAR_USER%

install:
- cmd: C:\\Miniconda\\python C:\\condaci.py auto ./conda --binstaruser %BINSTAR_USER% --binstarkey %BINSTAR_KEY%

notifications:
  - provider: Slack
    auth_token:
      secure: Jyd2NTPkBrrwBnl1C0mkNp5sUPGXzKrDgpZVDvPj72OUJtovXsO3795UsvktLucG
    channel: general
    on_build_status_changed: true
    on_build_success: false
    on_build_failure: false
